# Generated by Django 6.0.7 on 2026-09-01 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=50, unique=True, verbose_name='ID Alerte')),
                ('alert_type', models.CharField(choices=[('A1', 'Absence de données'), ('A2', 'Anomalie capteur'), ('A3', 'Batterie faible'), ('A4', 'Problème de qualité')], max_length=2, verbose_name='Type')),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('ACK', 'Acquittée'), ('INP', 'En cours'), ('RES', 'Résolue'), ('IGN', 'Ignorée')], default='NEW', max_length=3, verbose_name='Statut')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('details', models.JSONField(default=dict, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_reason', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alerts_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
