# Generated by Django 6.0.7 on 2026-09-11 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID Station')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('station_type', models.CharField(choices=[('SYNOP', 'Synoptique'), ('AWS', 'Automatique'), ('CLIMAT', 'Climatologique'), ('RAIN', 'Pluviométrique')], default='AWS', max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('OK', 'Opérationnelle'), ('WARNING', 'En alerte'), ('DOWN', 'En panne'), ('MAINTENANCE', 'En maintenance'), ('INACTIVE', 'Inactive')], default='OK', max_length=20, verbose_name='Statut')),
                ('manufacturer', models.CharField(blank=True, max_length=50, verbose_name='Fabricant')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Modèle')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de série')),
                ('frequency', models.IntegerField(default=10, verbose_name='Fréquence (minutes)')),
                ('last_data_received', models.DateTimeField(blank=True, null=True, verbose_name='Dernière donnée reçue')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('maintenance_until', models.DateTimeField(blank=True, null=True, verbose_name="Maintenance jusqu'au")),
                ('maintenance_reason', models.TextField(blank=True, verbose_name='Raison de la maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.region', verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'db_table': 'stations_stations',
                'ordering': ['name'],
            },
        ),
    ]
