# Generated by Django 6.0.7 on 2026-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbole')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Valeur min')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Valeur max')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'db_table': 'core_parameters',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la région')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code région')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'db_table': 'core_regions',
                'ordering': ['name'],
            },
        ),
    ]
