# Generated by Django 6.0.7 on 2026-09-11 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField(verbose_name="Date d'observation")),
                ('original_value', models.FloatField(verbose_name='Valeur originale')),
                ('corrected_value', models.FloatField(verbose_name='Valeur corrigée')),
                ('correction_reason', models.CharField(max_length=100, verbose_name='Raison')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('corrected_at', models.DateTimeField(auto_now_add=True, verbose_name='Corrigé le')),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Corrigé par')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.parameter', verbose_name='Paramètre')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Correction de données',
                'verbose_name_plural': 'Corrections de données',
                'db_table': 'quality_datacorrections',
                'unique_together': {('station', 'observation_date', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='QualityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField()),
                ('flag', models.IntegerField(choices=[(0, 'Bonne qualité'), (1, 'Suspecte'), (2, 'Erronée'), (9, 'Manquante')], default=0)),
                ('test_failed', models.CharField(blank=True, max_length=100, verbose_name='Test échoué')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.parameter')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'verbose_name': 'Flag de qualité',
                'verbose_name_plural': 'Flags de qualité',
                'db_table': 'quality_flags',
                'unique_together': {('station', 'observation_date', 'parameter')},
            },
        ),
    ]
