# Generated by Django 6.0.7 on 2026-09-17 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField(db_index=True, verbose_name="Date d'observation")),
                ('reception_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de réception')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Température (°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humidité (%)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Vitesse du vent (m/s)')),
                ('wind_direction', models.FloatField(blank=True, null=True, verbose_name='Direction du vent (°)')),
                ('pressure_qff', models.FloatField(blank=True, null=True, verbose_name='Pression QFF (hPa)')),
                ('precipitation', models.FloatField(blank=True, null=True, verbose_name='Précipitations (mm)')),
                ('quality_flag', models.IntegerField(choices=[(0, 'Bonne qualité'), (1, 'Suspecte'), (2, 'Erronée'), (9, 'Manquante')], default=0, verbose_name='Flag de qualité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='stations.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'db_table': 'observations_observation',
                'ordering': ['-observation_date'],
                'indexes': [models.Index(fields=['station', 'observation_date'], name='observation_station_57ed36_idx'), models.Index(fields=['observation_date'], name='observation_observa_0b9a75_idx')],
                'unique_together': {('station', 'observation_date')},
            },
        ),
    ]
